# Generated by Django 4.2.5 on 2023-09-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_lesson_productset1'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatchPASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeWatch', models.DurationField()),
                ('nameLesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsite.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('VideoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsite.videowatchpass')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
                'ordering': ('name',),
            },
        ),
    ]
