# Generated by Django 4.2.5 on 2023-09-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0005_remove_usercustom_videoid_usercustom_timewatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'ordering': ('name',), 'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзер'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='secondsLesson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='TimeWatch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
