# Generated by Django 4.2.5 on 2023-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0006_alter_usercustom_options_alter_lesson_secondslesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='productSet1',
        ),
        migrations.AddField(
            model_name='product',
            name='lessonsList',
            field=models.ManyToManyField(to='appsite.lesson'),
        ),
    ]
