# Generated by Django 4.2.5 on 2023-09-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsite', '0006_alter_usercustom_options_alter_lesson_secondslesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('OpenProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsite.product')),
            ],
            options={
                'verbose_name': 'Доступ к продуктам',
                'verbose_name_plural': 'Доступ к продуктам',
                'ordering': ('name',),
            },
        ),
    ]
