# Generated by Django 4.2.5 on 2023-09-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0007_remove_lesson_productset1_product_lessonslist'),
        ('appuser', '0002_alter_usercustompermission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustompermission',
            name='LessonsProd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsite.lesson'),
        ),
    ]
